### ISSUE TITLE
Superceded by upstream ruby-debug/ruby-debug?

### ISSUE THREAD

**Issue by ivoanjo** [jruby/jruby-debug#9]
I was looking into `jruby-debug` and it seems that the latest releases are based off https://github.com/ruby-debug/ruby-debug instead, not from the codebase in this repository.

This is a bit confusing. Should this repository be updated with a message saying that the gem is now maintained elsewhere? I don't mind opening up the PR for it, but wanted to doublecheck if I was not mistaken first.

Thanks!

**Comment by JasonLunn** [comment]
Ran into this today - got a stack trace while debugging my SimpleCov integration that pointed to line 131 in Util.java, which doesn't exist in this repo. Thanks for the pointer.

**Comment by JasonLunn** [comment]
@headius - would you consider putting a sign post in README telling visitors where to go?

**Comment by headius** [comment]
I do believe this repository is defunct now that the upstream ruby-debug contains code. We (@enebo) even worked with them recently to make fixes and get a new release out.

@enebo Can you confirm this repository could be deleted?

**Comment by headius** [comment]
Actually I realize now that the changes @enebo made were to this repository, such as this one:

https://github.com/jruby/jruby-debug/commit/010dc82532e61b7a2e04a43d40afd31c768d147b

It's a bit confusing, though (even for me it seems) so perhaps we can document it a bit better.

**Comment by enebo** [comment]
@headius yeah I was also confused by it.  but I committed there first then did a commit on ruby-debug after it.

**Comment by enebo** [comment]
Added a note in 821b5b1
